##json结构超类
#server:
#  port: 8082
#  servlet:
#    context-path: /api
#logging:
#  level:
#    root: info
#    com.hehanpeng: debug
#  file: logs/my.log

spring:
  profiles:
    active: sit
  thymeleaf:
    mode: HTML
  devtools:
    restart:
      trigger-file: .trigger
#  mvc:
#    static-path-pattern: /static/**

###自定义属性
book:
  name: 射雕英雄传
  author: 金庸
  isbn: ${random.uuid}
  description: ${book.name},属于武侠小说

# application-{pro}.yml
