##json结构超类
server:
  port: 8080
#  servlet:
#    context-path: /api
logging:
  level:
    root: info
    com.hehanpeng: debug
  file: logs/sit.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.81.134:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

###自定义属性
#book:
#  name: 射雕英雄传
#  author: 金庸
#  isbn: ${random.uuid}
#  description: ${book.name},属于武侠小说